version: '3.8'

services:
  postgres:
    image: postgres:17.2
    container_name: postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: devops_training_db
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/devops_training_db
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: password
    ports:
        - "8080:8080"
    depends_on:
        - postgres

volumes:
  postgres_data:





