apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose-windows-amd64.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: spring-app
  name: spring-app
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: spring-app
